#!/bin/bash

# Exit immediately on error, disallow undefined variables, fail on pipe errors
set -euo pipefail

# Color definitions
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Set script directory
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "$SCRIPT_DIR"

# Set output directories
OUTPUT_DIR="${SCRIPT_DIR}/output"
ARCHIVES_DIR="${OUTPUT_DIR}/archives"
XCFRAMEWORK_DIR="${OUTPUT_DIR}/xcframeworks"

# Project configuration
PROJECT_NAME="LynxPrebuild"
WORKSPACE_NAME="${PROJECT_NAME}.xcworkspace"
SCHEME_NAME="Pods-${PROJECT_NAME}"

# Build configuration (Debug or Release)
BUILD_CONFIGURATION="Release"

echo -e "${GREEN}========================================${NC}"
echo -e "${GREEN} Starting Lynx XCFramework Build${NC}"
echo -e "${GREEN}========================================${NC}"
echo ""

# Clean previous build artifacts
echo -e "${YELLOW}1. Cleaning previous build artifacts...${NC}"
rm -rf "$OUTPUT_DIR"
mkdir -p "$ARCHIVES_DIR"
mkdir -p "$XCFRAMEWORK_DIR"

# Build iOS Simulator Archive
echo ""
echo -e "${YELLOW}2. Building iOS Simulator (iphonesimulator) Archive...${NC}"
echo "   Target architectures: x86_64, arm64"

if ! xcodebuild archive \
    -workspace "$WORKSPACE_NAME" \
    -scheme "$SCHEME_NAME" \
    -configuration "$BUILD_CONFIGURATION" \
    -destination "generic/platform=iOS Simulator" \
    -archivePath "${ARCHIVES_DIR}/${PROJECT_NAME}-iphonesimulator.xcarchive" \
    -sdk iphonesimulator \
    -quiet \
    SKIP_INSTALL=NO \
    BUILD_LIBRARY_FOR_DISTRIBUTION=YES; then
    echo -e "${RED}❌ iOS Simulator Archive build failed${NC}"
    exit 1
fi
echo -e "${GREEN}✅ iOS Simulator Archive build completed${NC}"

# Build iOS Device Archive
echo ""
echo -e "${YELLOW}3. Building iOS Device (iphoneos) Archive...${NC}"
echo "   Target architecture: arm64"

if ! xcodebuild archive \
    -workspace "$WORKSPACE_NAME" \
    -scheme "$SCHEME_NAME" \
    -configuration "$BUILD_CONFIGURATION" \
    -destination "generic/platform=iOS" \
    -archivePath "${ARCHIVES_DIR}/${PROJECT_NAME}-iphoneos.xcarchive" \
    -sdk iphoneos \
    -quiet \
    SKIP_INSTALL=NO \
    BUILD_LIBRARY_FOR_DISTRIBUTION=YES; then
    echo -e "${RED}❌ iOS Device Archive build failed${NC}"
    exit 1
fi
echo -e "${GREEN}✅ iOS Device Archive build completed${NC}"

# Find all frameworks in archives and create XCFrameworks
echo ""
echo -e "${YELLOW}4. Creating XCFrameworks...${NC}"

FRAMEWORK_COUNT=0

while IFS= read -r -d '' SIMULATOR_FRAMEWORK_PATH; do
    FRAMEWORK_NAME=$(basename "$SIMULATOR_FRAMEWORK_PATH")
    FRAMEWORK_BASE_NAME="${FRAMEWORK_NAME%.framework}"

    # Skip the CocoaPods umbrella target (Pods-LynxPrebuild -> Pods_LynxPrebuild).
    # It is a static aggregate that only exists to link the pods together, not a
    # distributable dependency.
    if [[ "$FRAMEWORK_BASE_NAME" =~ ^Pods[-_] ]]; then
        echo ""
        echo "Skipping umbrella framework: $FRAMEWORK_NAME"
        continue
    fi

    DEVICE_FRAMEWORK_PATH="${ARCHIVES_DIR}/${PROJECT_NAME}-iphoneos.xcarchive/Products/Library/Frameworks/${FRAMEWORK_NAME}"

    if [ ! -d "$DEVICE_FRAMEWORK_PATH" ]; then
        echo -e "${RED}❌ iOS Device Framework not found: ${FRAMEWORK_NAME}${NC}"
        exit 1
    fi

    echo ""
    echo "Processing: $FRAMEWORK_NAME"

    if ! xcodebuild -create-xcframework \
        -framework "$SIMULATOR_FRAMEWORK_PATH" \
        -framework "$DEVICE_FRAMEWORK_PATH" \
        -output "${XCFRAMEWORK_DIR}/${FRAMEWORK_BASE_NAME}.xcframework"; then
        echo -e "${RED}❌ XCFramework creation failed: ${FRAMEWORK_NAME}${NC}"
        exit 1
    fi

    echo -e "${GREEN}✅ ${FRAMEWORK_BASE_NAME}.xcframework created${NC}"
    FRAMEWORK_COUNT=$((FRAMEWORK_COUNT + 1))
done < <(find "${ARCHIVES_DIR}/${PROJECT_NAME}-iphonesimulator.xcarchive/Products/Library/Frameworks" -maxdepth 1 -name "*.framework" -type d -print0)

# Assert the built set is exactly what CocoaPods embeds into an app.
#
# The release set is derived from this build rather than from a hand-maintained
# list, so without an independent cross-check nothing would notice a framework
# that quietly stops being produced -- it would just be missing from the release.
# The manifest is generated by `pod install`, a prerequisite of this script, and
# is the same file Xcode runs to embed frameworks at build time.
echo ""
echo -e "${YELLOW}5. Verifying built XCFrameworks against the CocoaPods manifest...${NC}"

MANIFEST="${SCRIPT_DIR}/Pods/Target Support Files/${SCHEME_NAME}/${SCHEME_NAME}-frameworks.sh"

if [ ! -f "$MANIFEST" ]; then
    echo -e "${RED}❌ CocoaPods framework manifest not found: ${MANIFEST}${NC}"
    exit 1
fi

EXPECTED_FRAMEWORKS=$(grep -oE 'install_framework "[^"]+\.framework"' "$MANIFEST" \
    | sed -E 's#.*/([^/"]+)\.framework"$#\1#' \
    | sort -u) || true
BUILT_FRAMEWORKS=$(find "$XCFRAMEWORK_DIR" -maxdepth 1 -name "*.xcframework" -type d \
    -exec basename {} .xcframework \; \
    | sort) || true

if [ -z "$EXPECTED_FRAMEWORKS" ]; then
    echo -e "${RED}❌ No embedded frameworks could be parsed from ${MANIFEST}${NC}"
    exit 1
fi

if [ "$EXPECTED_FRAMEWORKS" != "$BUILT_FRAMEWORKS" ]; then
    echo -e "${RED}❌ Built XCFrameworks do not match what CocoaPods embeds${NC}"
    echo "   '<' expected from manifest, '>' actually built:"
    diff <(echo "$EXPECTED_FRAMEWORKS") <(echo "$BUILT_FRAMEWORKS") || true
    exit 1
fi

echo -e "${GREEN}✅ All ${FRAMEWORK_COUNT} embedded frameworks accounted for${NC}"

# Display results
echo ""
echo -e "${GREEN}========================================${NC}"
echo -e "${GREEN} ✅ Build Completed! (${FRAMEWORK_COUNT} XCFrameworks)${NC}"
echo -e "${GREEN}========================================${NC}"
echo ""
echo "Generated XCFrameworks:"
for xcframework in "${XCFRAMEWORK_DIR}"/*.xcframework; do
    if [ -d "$xcframework" ]; then
        echo "  - $(basename "$xcframework")"
    fi
done
echo ""
echo "Output: ${XCFRAMEWORK_DIR}"

# Clean up intermediate build artifacts
rm -rf "$ARCHIVES_DIR"
